name: dxjoke Tectonic Docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Compile momentum_equation.tex
        run: docker run --mount src=$GITHUB_WORKSPACE,target=/usr/src/tex,type=bind dxjoke/tectonic-docker:latest /bin/sh -c "tectonic momentum_equation.tex"
      - name: Upload momentum_equation.pdf
        uses: actions/upload-artifact@v2
        with:
          name: momentum_equation.zip
          path: momentum_equation.pdf

